[phases.setup]
nixPkgs = ["nodejs", "cacert", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "mesa", "libgbm", "expat", "libxcb"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"
