[phases.setup]
nixPkgs = ["...", "chromium", "glib", "nss", "atk", "at-spi2-atk", "libdrm", "mesa", "libgbm", "expat", "libxcb"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
